name: Python CI + Deploy a GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ejecutar script de suma
        run: python scripts/suma.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir artefacto web
        uses: actions/upload-pages-artifact@v3
        with:
          path: web

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
