name: Deploy Web App to GitHub Pages 🚀

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Probar ejecucion en Python
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: python sumar.py

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Empaquetar arte de la Web App
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4